env:
  node: true
  es2021: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  no-console: off
  import/prefer-default-export: off
  import/extensions: [warn, { js: ignorePackages }]
  prettier/prettier: [warn, { singleQuote: true }]
